DROP TABLE IF EXISTS `database_example`;
CREATE TABLE `database_example` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(30) NULL DEFAULT NULL COLLATE 'utf16_bin',
	`description` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf16_bin',
	`url` VARCHAR(120) NULL DEFAULT NULL COLLATE 'utf16_bin',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf16_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1
;